services:
  - type: web
    name: micromoon
    env: node
    plan: free
    region: frankfurt
    startCommand: "node server.js"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_SSL
        value: "false"
    healthCheckPath: "/health"
    autoDeploy: true
databases:
  - name: micromoon-db
